### ISSUE TITLE
Issues in cluster analysis

### ISSUE THREAD

**Issue by ProteoPyViz** [ag-warscheid/autoprot#38]
Column names are not properly displayed in traces for more then one
and are completely skipped when using z-transformation.

**Comment by aretaon** [comment]
Could you provide a code example, ideally a minimal working example or an error traceback?

**Comment by ProteoPyViz** [comment]
Our "normal" example datasets should result in the same errors.
Just set the zs parameter to 1 for column transformation.

c = clst.HCA(data[cols], zs=1)
